// Each file adds one project to PORTFOLIO_PROJECTS.
// tier 1 = first featured card | 2 = second | 3 = third | no tier = explorer only
window.PORTFOLIO_PROJECTS = window.PORTFOLIO_PROJECTS || [];
window.PORTFOLIO_PROJECTS.push({
    title: 'RPA Extracting',

    description: `Since braskem is also a research company, it has a lot of equipament to run analytical techniques, and often these equipament have their own software to treat the data the equipament generate. 
    Since braskem is a huge company, a lot of analysis are done and takes a lot of time to work manually on those softwares to extract the data generated by the equipament. Hence, to save analists time, soma automations (RPA) were developed to extract the data automagically from the softwares. Also, some automations envolved extract data from files such as pdfs and images.`,

    // tier: null,

    sub_topic: 'Braskem',

    // FontAwesome icon (e.g. 'fas fa-folder-open', 'fas fa-brain', 'fas fa-chart-line')
    // icon: 'fas fa-car-side',

    // Available colors: neon-blue | neon-purple | neon-green
    // accent_color: 'neon-blue',

    // background_image: 'assets/porsche_logo.png',

    tech: ['pyautogui', 'tesseract', 'OpenCV', 'tkinter'],

    // github_url: '#',
    
    // live_url: '#'
});
