// Each file adds one project to PORTFOLIO_PROJECTS.
// tier 1 = first featured card | 2 = second | 3 = third | no tier = explorer only
window.PORTFOLIO_PROJECTS = window.PORTFOLIO_PROJECTS || [];
window.PORTFOLIO_PROJECTS.push({
    title: 'RPA Extracting',

    summary: `RPA automations to extract data generated by lab equipment and from PDFs/images, saving analysts hours of repetitive manual work across multiple analytical techniques at Braskem.`,

    description: `As a research-driven company, Braskem operates a wide range of equipment for analytical techniques, much of which relies on proprietary software to process the data it generates. Given the company's scale, a high volume of analyses is performed, and manually extracting results from these various software tools was highly time-consuming. 
    To address this, I developed a set of RPA automations to extract the generated data directly from the software automatically. Some of these automations also handled data extraction from other sources, such as PDF files and images.`,

    tech: ['pyautogui', 'tesseract', 'OpenCV', 'tkinter'],

    sub_topic: 'Braskem',
    
    outcomes: `Previously, analysts spent hours at the workstation manually retrieving analysis results. With these automations, results are now extracted and sent to the cloud automatically, saving analysts hours of repetitive work.`,
});
