// Each file adds one project to PORTFOLIO_PROJECTS.
// tier 1 = first featured card | 2 = second | 3 = third | no tier = explorer only
window.PORTFOLIO_PROJECTS = window.PORTFOLIO_PROJECTS || [];
window.PORTFOLIO_PROJECTS.push({
    title: 'RPA Extracting',

    summary: `RPA automations to extract data generated by lab equipment and from PDFs/images, saving analysts hours of repetitive manual work across multiple analytical techniques at Braskem.`,

    description: `Since braskem is also a research company, it has a lot of equipament to run analytical techniques, and often these equipament have their own software to treat the data the equipament generate. 
    Since braskem is a huge company, a lot of analysis are done and takes a lot of time to work manually on those softwares to extract the data generated by the equipament. Hence, to save analists time, soma automations (RPA) were developed to extract the data automagically from the softwares. Also, some automations envolved extract data from files such as pdfs and images.`,

    tech: ['pyautogui', 'tesseract', 'OpenCV', 'tkinter'],

    sub_topic: 'Braskem',
    
    // outcomes: ``,
});
